# -*- coding: utf-8 -*-
{
    'name': "Construction Tenders",
    'version': "1.1",
    'summary': """
    Construction Tenders,
    Offer,
    Version,
    Project Management,
    Construction,
    Tenders,
    Owner Contract,
    Subcontractor,
    Subcontractor Contract,
    Construction Management System (CMS),
    Completion Request,
    Tasks, delivery requests,
    Work Breakdown Structure (WBS),
    Work Breakdown Template (WBT),
    units,
    jobs,
    Dashboard,
    """,

    'description': """
    A system for managing the bidding process for construction projects.
    """,

    'category': 'Project',
    'author': 'Neoteric Hub',
    'company': 'Neoteric Hub',
    'live_test_url': '',
    'price': 800.00,
    'currency': 'USD',
    'website': 'https://www.neoterichub.com',

    'depends': ['nthub_constructions', 'account', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/tender_offer_sequence.xml',
        'data/tender_offer_version_sequence.xml',
        'data/variation_order_sequence.xml',
        'wizards/new_version_wizard_view.xml',
        'wizards/import_tender_items_wizard_view.xml',
        'wizards/down_payment_invoice_wizard_view.xml',
        'wizards/jobcost_copy_choice_wizard_view.xml',
        'views/templates.xml',
        'views/top_sheet.xml',
        'views/tender_information.xml',
        'views/tender_offer_views.xml',
        'views/tender_offer_version_views.xml',
        'views/construction_project.xml',
        'views/project_tender.xml',
        'views/overhead_type_views.xml',
        'views/tender_deduction_type_views.xml',
        'views/contract_deduction_inherit_views.xml',
        'views/owner_contract.xml',
        'views/tender_job_cost_views.xml',
        'views/variation_order_views.xml',
        'views/completion_request_inherit_views.xml',
        'views/sub_contract_delivery_inherit_views.xml',
        'views/res_partner_inherit_views.xml',
        'views/project_task_menu_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu_views.xml',
        'report/offer_report.xml',
        'report/top_sheet_report.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
