# -*- coding: utf-8 -*-
{
    'name': 'Product Requisitions',
    'version': '1.0',
    'summary': """
    project requisitions,
    fleet,
    purchase,
    purchase requisition,
    internal picking,
    purchase order,
    Construction Tenders,
    Offer,
    Version,
    Project Management, 
    Construction, 
    Tenders, 
    Owner Contract, 
    Subcontractor, 
    Subcontractor Contract,
    Construction Management System (CMS), 
    Completion Request, 
    Tasks, delivery requests, 
    Work Breakdown Structure (WBS), 
    Work Breakdown Template (WBT),
    units, 
    jobs, 
    Dashboard,
    """,
    'description': """
    This module allow your employees/users to create Purchase Requisitions
    """,
    'category': 'Project',
    'author': 'Neoteric Hub',
    'company': 'Neoteric Hub',
    'live_test_url': '',
    'price': 350.00,
    'currency': 'USD',
    'website': 'https://www.neoterichub.com',
    'depends': ['stock', 'hr', 'purchase', 'project',],
    'data': [
        'security/security.xml',
        'security/multi_company_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/purchase_requisition_sequence.xml',
        'data/employee_purchase_approval_template.xml',
        'data/confirm_template_material_purchase.xml',
        'report/purchase_requisition_report.xml',
        'views/purchase_requisition_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_department_view.xml',
        'views/stock_picking_view.xml',
        'views/project.xml',
    ],
    'images': ['static/description/banner.gif'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
